### ISSUE TITLE
Starting virtual device fails

### ISSUE THREAD

**Issue by tobi-coder** [actions-on-google/smart-home-local#30]
Starting the virtual device with the command

`npm start --prefix device/ -- --device_id strand1 --discovery_protocol UDP --control_protocol TCP --channel 1
`

Fails with the error:

```
/home/pi/www/smart-home-local/device/server.ts:30
import {IOPCMessage} from './types';
    ^
TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at /home/pi/www/smart-home-local/device/server.ts:22:12
    at __importStar (/home/pi/www/smart-home-local/device/server.ts:30:5)
    at Object.<anonymous> (/home/pi/www/smart-home-local/device/server.ts:26:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module.m._compile (/home/pi/www/smart-home-local/device/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (/home/pi/www/smart-home-local/device/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pi/www/smart-home-local/device/main.ts:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module.m._compile (/home/pi/www/smart-home-local/device/node_modules/ts-node/src/index.ts:439:23)
```

**Comment by devunwired** [comment]
Looks like this may be due to a recent regresstion in `tslib`: https://github.com/microsoft/tslib/issues/102

Proppy, can you take a look?
