### ISSUE TITLE
npm run deploy --prefix functions happen some error

### ISSUE THREAD

**Issue by sss22213** [actions-on-google/smart-home-local#51]
HI!

when i  run "npm run deploy --prefix functions", and happening problem.

```
node_modules/@google-cloud/firestore/types/firestore.d.ts:1629:8 - error TS2304: Cannot find name 'AsyncIterable'.

1629     ): AsyncIterable<QueryPartition<T>>;
            ~~~~~~~~~~~~~
```

detail:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.10
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle smarthome-provider-placeholder@0.0.1~prebuild: smarthome-provider-placeholder@0.0.1
6 info lifecycle smarthome-provider-placeholder@0.0.1~build: smarthome-provider-placeholder@0.0.1
7 verbose lifecycle smarthome-provider-placeholder@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle smarthome-provider-placeholder@0.0.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/usb2/smart-home-local/functions/node_modules/.bin:/usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/usb2/smart-home-local/functions/node_modules/.bin:/mnt/usb2/esp-idf/components/esptool_py/esptool:/mnt/usb2/esp-idf/components/espcoredump:/mnt/usb2/esp-idf/components/partition_table:/mnt/usb2/esp-idf/components/app_update:/home/an/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin:/home/an/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin:/home/an/.espressif/tools/xtensa-esp32s3-elf/esp-2020r3-8.4.0/xtensa-esp32s3-elf/bin:/home/an/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/home/an/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/home/an/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/bin:/home/an/.espressif/python_env/idf4.3_py2.7_env/bin:/mnt/usb2/esp-idf/tools:/opt/sifive/JLink_Linux_V686g_x86_64:/opt/sifive/JLink_Linux_V686g_x86_64:/opt/sifive/JLink_Linux_V686g_x86_64:/opt/sifive/riscv-qemu-4.2.0-2020.04.0-x86_64-linux-ubuntu14:/opt/ros/noetic/bin:/home/an/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/an/.dotnet/tools
9 verbose lifecycle smarthome-provider-placeholder@0.0.1~build: CWD: /mnt/usb2/smart-home-local/functions
10 silly lifecycle smarthome-provider-placeholder@0.0.1~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle smarthome-provider-placeholder@0.0.1~build: Returned: code: 2  signal: null
12 info lifecycle smarthome-provider-placeholder@0.0.1~build: Failed to exec build script
13 verbose stack Error: smarthome-provider-placeholder@0.0.1 build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid smarthome-provider-placeholder@0.0.1
15 verbose cwd /mnt/usb2/smart-home-local/functions
16 verbose Linux 5.4.0-58-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 2
22 error smarthome-provider-placeholder@0.0.1 build: `tsc`
22 error Exit status 2
23 error Failed at the smarthome-provider-placeholder@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
I have no idea to solve it.
Thanks in advance.

**Comment by proppy** [comment]
Can you paste the output of `npm ls --depth`?
